version: '3'
services:
  main:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m
      timeout: 10s
      retries: 3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"